name: Deployment Pipeline

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    env:
      SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
      SERVER_IP: ${{ secrets.SERVER_IP }}
      USER: ${{ secrets.SERVER_USER }}

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Environment Variables
        run: |
          echo "Server IP: $SERVER_IP"
          echo "User: $USER"

      - name: Set Up SSH
        run: |
          # Setup SSH
          mkdir -p ~/.ssh
          echo "$SSH_PRIVATE_KEY" | tr -d '\r' > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan -H $SERVER_IP >> ~/.ssh/known_hosts
            chmod 644 ~/.ssh/known_hosts


      - name: SSH Into Web Server, Fetch Latest Changes and Run Changes
        run: |
          ssh $USER@$SERVER_IP -i ~/.ssh/id_rsa
          gh repo clone dohoudaniel/fastapi-book-project
          cd fastapi-book-project
          git pull
          python3.10 -m venv venv
          source venv/bin/activate
          python -m ensurepip --upgrade
          pip install --upgrade pip
          pip install -r requirements.txt
          uvicorn main:app --host 0.0.0.0 --port 8000 --reload

